// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package proto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFebee679DecodeGithubComSamyfodilWeb3authJson(in *jlexer.Lexer, out *InitReply) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "challenge":
			out.Challenge = string(in.String())
		case "signature":
			out.Signature = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFebee679EncodeGithubComSamyfodilWeb3authJson(out *jwriter.Writer, in InitReply) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Challenge != "" {
		const prefix string = ",\"challenge\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Challenge))
	}
	if in.Signature != "" {
		const prefix string = ",\"signature\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Signature))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InitReply) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFebee679EncodeGithubComSamyfodilWeb3authJson(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InitReply) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFebee679EncodeGithubComSamyfodilWeb3authJson(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InitReply) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFebee679DecodeGithubComSamyfodilWeb3authJson(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InitReply) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFebee679DecodeGithubComSamyfodilWeb3authJson(l, v)
}
func easyjsonFebee679DecodeGithubComSamyfodilWeb3authJson1(in *jlexer.Lexer, out *InitMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFebee679EncodeGithubComSamyfodilWeb3authJson1(out *jwriter.Writer, in InitMessage) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Address != "" {
		const prefix string = ",\"address\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InitMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFebee679EncodeGithubComSamyfodilWeb3authJson1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InitMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFebee679EncodeGithubComSamyfodilWeb3authJson1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InitMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFebee679DecodeGithubComSamyfodilWeb3authJson1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InitMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFebee679DecodeGithubComSamyfodilWeb3authJson1(l, v)
}
